### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [JalenPage/jalens-app5#1]
This isn't _quite_ what I was looking for. I actually wanted the content split into [two separate columns](http://codekwondo.herokuapp.com/showcases/337). Can you fix this, then push up a new version?

**Comment by JalenPage** [comment]
I have added the image in each of my html files into a column of its own. Is this what you were looking for or am I still doing this incorrectly? 

On Tuesday, February 17, 2015 3:09 PM, Chris Fritz notifications@github.com wrote:

This isn't quite what I was looking for. I actually wanted the content split into two separate columns. Can you fix this, then push up a new version?

**Comment by chrisvfritz** [comment]
I'm actually looking for 2 columns, side by side, that collapse on top of each other on smaller screen widths, [like this](https://mysterious-falls-8477.herokuapp.com/).

**Comment by chrisvfritz** [comment]
:+1: Much better now.
